#!/bin/sh
set -e

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnishd \
	    -F \
	    -f /etc/varnish/default.vcl \
	    -a :${VARNISH_HTTP_PORT:-6081} \
	    -T 127.0.0.1:6082 \
	    -u varnish \
	    -g varnish \
	    -t 120 \
	    -p http_range_support=off \
	    -s malloc,$VARNISH_SIZE \
	    "$@"
fi

exec "$@"
